web:
  image: ufpel/cobalto-web:so_debian-10-buster_php-7.1.33_img-v1.0.0 
  ports:
    - "80:80"
  links:
    - dbpostgres
    - dbmysql
  volumes:
    - .:/var/www/html
    - ./docker/:/usr/local/etc/php
  environment:
    PHPAR_MYSQL: mysql://root:password@dbmysql/phpar_test
    PHPAR_PGSQL: pgsql://postgres:password@dbpostgres/phpar_test
  entrypoint: sh /var/www/html/docker/init.sh 

dbpostgres:
  image: ufpel/cobalto-postgres:so_ubuntu-alpine_app-9.5_img-v1.0.0
  ports:
    - "5432:5432"
  environment:
      POSTGRES_DB: cobalto-desenv
      POSTGRES_USER: cobalto-desenv
      POSTGRES_PASSWORD: cobalto-desenv

dbmysql:
  image: mysql:5.7.30
  ports:
    - "3306:3306"
  environment:
    MYSQL_DATABASE: phpar_test
    #    MYSQL_USER: root
    #    MYSQL_PASSWORD: password
    MYSQL_ROOT_PASSWORD: password

#MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD
