web:
  image: php:5.6.40-fpm-alpine
  ports:
    - "80:80"
  links:
    - dbpostgres
    - dbmysql
  volumes:
    - .:/var/www/html
    - ./docker/:/usr/local/etc/php
  environment:
    PHPAR_MYSQL: mysql://root:password@dbmysql/phpar_test
    PHPAR_PGSQL: pgsql://postgres:password@dbpostgres/phpar_test
  entrypoint: sh /var/www/html/docker/init.sh 

dbpostgres:
  image: postgres:9.5-alpine
  ports:
    - "5432:5432"
  environment:
    POSTGRES_DB: phpar_test
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password

dbmysql:
  image: mysql:5.7.30
  ports:
    - "3306:3306"
  environment:
    MYSQL_DATABASE: phpar_test
    #    MYSQL_USER: root
    #    MYSQL_PASSWORD: password
    MYSQL_ROOT_PASSWORD: password

#MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD
