web-record:
  image: php:7.1.33-apache-buster
  ports:
    - "80:80"
  links:
    - dbpostgres
    - dbmysql
  volumes:
    - .:/var/www/html

  environment:
    PHPAR_MYSQL: mysql://root:pass@dbmysql/dbname
    PHPAR_PGSQL: pgsql://user:pass@dbpostgres/dbname
  entrypoint: sh /var/www/html/docker/init.sh 

dbpostgres:
  image: ufpel/cobalto-postgres:so_ubuntu-alpine_app-9.5_img-v1.0.0
  volumes:
    - .:/var/www/html
    - ./test/sql/pgsql.sql:/docker-entrypoint-initdb.d/pgsql.sql:rw
  ports:
    - "5432:5432"
  environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      #BASH_SOURCE: /var/www/html/docker/pginit.sh 
      #psql -Uuser -W -d dbname -f /var/www/html/test/sql/pgsql.sql

dbmysql:
  image: mysql:5.7.30
  volumes:
    - .:/var/www/html
    - ./test/sql/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql:rw
  ports:
    - "3306:3306"
  environment:
    MYSQL_DATABASE: dbname
    MYSQL_PASSWORD: pass
    MYSQL_ROOT_PASSWORD: pass
  
    #no terminal executar: mysql -u root -ppass -D dbname < /var/www/html/test/sql/mysql.sql

#MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD
